### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by marcs94** [mcarfagno/mpc_python#2]
Hi! I started the simulation, but it doesn't work; vehicle doesn't move

**Comment by mcarfagno** [comment]
Hello! If you mean the `pybullet` simulation, the terminal from which you started the python script should prompt after all physics elements are finished loading like so:
![Screenshot 2022-07-21 12:04:19](https://user-images.githubusercontent.com/22679370/180200523-dc2d222d-8dea-41bc-a084-69bf39b7484a.png)

Should start moving after that:
![Screenshot 2022-07-21 12:09:08](https://user-images.githubusercontent.com/22679370/180200624-5202affe-3f52-4af2-874f-549bdbe2af4c.png)

Does this fixes the issue?

**Comment by marcs94** [comment]
Thanks for the reply! Yes, I get this screen and then I press the enter key to start the simulation, but the vehicle remains stationary. Furthermore, the wheels of the vehicle are not seen, only the chassis appears but it is all black; I show you what appears to me, so you understand better:
![Schermata da 2022-07-22 01-58-24](https://user-images.githubusercontent.com/51294891/180334174-eb76aeac-87a6-4252-b6c7-8ae833e24f98.png)

**Comment by mcarfagno** [comment]
I see what you mean, it seems an issue when loading the meshes from the `.urdf` file. Could you please copy the output of the terminal (before the "press enter" user input).

**Comment by marcs94** [comment]
![Schermata da 2022-07-22 20-29-12](https://user-images.githubusercontent.com/51294891/180501746-8453c977-1156-465a-936a-bf885dc4f630.png)
![Schermata da 2022-07-22 20-29-09](https://user-images.githubusercontent.com/51294891/180501749-3f14419d-7bea-41e9-9d6f-ee3014aac18c.png)

**Comment by mcarfagno** [comment]
Sorry for late reply, I do not see anything wrong with the log from pybullet (finds the GPU for rendering etc...)

Could you please try to run the script from within the `mpc_pybullet_demo` directory instead of the repo root dir? (I tested on both ubuntu 20.04 and 22.04, should work also in VSCode term)
```bash
cd ~/mpc_python/mpc_pybullet_demo
python3 mpc_demo_pybullet.py
```

**Comment by marcs94** [comment]
I've tried, but nothing, it not works... I have Ubuntu 18.04, probably is this the reason of the problem? 
Anyway, if I change the colours of the wheels, they appear, but are all in the same position, as if they were superimposed. maybe it is necessary to change the position of the wheels in the urdf file of the vehicle?

**Comment by mcarfagno** [comment]
You should not have to. 

The car urdf model is exactly the same as https://github.com/erwincoumans/pybullet_robots . Are you able to run just the car script from the official repo [f10_racecar.py](https://github.com/erwincoumans/pybullet_robots/blob/master/f10_racecar.py)?

**Comment by marcs94** [comment]
Sorry for late reply, but I'm on holiday, when i will return from holiday, i will try. But I will probably focus more on the other simulation, "mpc_demo_nosim"; it's well done, but there are some things that I didn't understand about MPC controller. If this is not a problem for you, I would like to clear up these doubts about the MPC controller by talking to you about it, either in private or by continuing to talk here.

PS: are you Italian?

**Comment by mcarfagno** [comment]
Yes I am indeed italian, I am keeping this thread in english so other users can understand if they have similar issues.

If you are fond of reading about MPC derivation, there are some [notebooks](https://github.com/mcarfagno/mpc_python/tree/master/notebooks) in this repo, otherwise here is some useful learning material:
- This, highly reccomended, [Coursera Specialization](https://www.coursera.org/lecture/intro-self-driving-cars/lesson-4-advanced-steering-control-mpc-WHPvn), videos are free
- The [course material](http://www.mpc.berkeley.edu/mpc-course-material) of prof Borrelly at Berkley uni includes a free pdf
- Matlab also has a nice [video series](https://www.youtube.com/watch?v=8U0xiOkDcmw)


If there are no more technical problems with the codebase then I will close this issue.

**Comment by marcs94** [comment]
Ok, thanks!
