### ISSUE TITLE
questions about mpc controller

### ISSUE THREAD

**Issue by giovanniapri** [mcarfagno/mpc_python#3]
Hi Marcello, there are some things that I don't understand about the mpc controller you implemented with the code in the "mpc_pybullet_demo" directory; they are 3 things:
1) is there a terminal constraint on the state (on the final state)?
2) is the implemented MPC controller linear or non-linear?
3) how can you prove that the mpc controller that you have implemented guarantees system stability?
Thank you very much!

**Comment by mcarfagno** [comment]
Hi, to answer your questions:
1. No, I recall doing some experiments with it and there was no significant improvement, the code for adding a final state cost should be the same as the one in the notebook `2.0 - mpc base` 
```
# Final Point tracking
cost += cp.quad_form(x[:, T] - x_ref[:, T], Qf)
```
And define the `Qf` matrix accordingly
Otherwise if you want to impose a hard constrain of the final state you can use the currently commented out line:
```
_constraints += [opt.norm(target[:, time_horizon] - x[:, time_horizon], 1) <= 0.01,
```
Keep in mind this is a hard constrain so the optimizer will fail if no solution that can respect this constrain is found.

2. So short answer is linear. Long answer is that this MPC problem is non-linear (because  the kinematic equations are not linear), but the python solver ([cvxpy](https://www.cvxpy.org/)) only handles **convex** problems (so only linear terms), you can read more about convex vs non-convex optimization [here](https://www.solver.com/convex-optimization). This means that I had to linearize the model, this is documented in the notebook [1,0-lti-system-modelling](https://github.com/mcarfagno/mpc_python/blob/master/notebooks/1.0-lti-system-modelling.ipynb).

3. Not sure I can help with that one, sorry

**Comment by giovanniapri** [comment]
ok. 
Is it true that the trajectory is entered in the augmented state formed by vehicle state + trajectory state? therefore the trajectory is completely known from the beginning

**Comment by mcarfagno** [comment]
If by augmented you intend like presented in [here](https://www.mathworks.com/help/mpc/ug/specify-prediction-model-for-nonlinear-mpc.html#mw_83f7a9b9-9841-45ba-8485-f18ebcc470d4) then no, but this seems related to disturbances rather than state and trajectory.

> therefore the trajectory is completely known from the beginning

The trajectory is known to the controller at the beginning of the optimization step, the state and and a trajectory are feed into the optimizer, see https://github.com/mcarfagno/mpc_python/blob/7f7cdf31b4ae57fd7c9428b4fec762d90e6368a7/mpc_pybullet_demo/mpc_demo_nosim.py#L116

and here for the implementation
https://github.com/mcarfagno/mpc_python/blob/master/mpc_pybullet_demo/mpcpy/utils.py#L69

**Comment by giovanniapri** [comment]
I was wondering if the states of the vehicle (x, y, speed, orientation) were joined to the trajectory and put all together in a single state, formed by the 4 states of the vehicle + the state of the trajectory, i.e. the point (x, y) of the trajectory. Apparently then this is not the case, rather the trajectory is seen as an exogenous input, as a disturbance for example
