### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by marcs94** [mcarfagno/mpc_python#4]
Dear Marcello,
I have some questions:
1) how did you generate the reference trajectory (did you use splines or something else)?
2) what is the equilibrium point of the system (i.e. of the vehicle)?
3) Are you sure acceleration is an input? I believe that more than an entrance, acceleration is a state, but maybe I'm wrong
4) from the code, I understand that you have applied the MPC control law on the non-linear system, and not on the linearized one. Am I wrong or am I right? And if I'm right, then why is done the linearization of the nonlinear model?

**Comment by mcarfagno** [comment]
Let's see:

1. see here https://github.com/mcarfagno/mpc_python/blob/7f7cdf31b4ae57fd7c9428b4fec762d90e6368a7/mpc_pybullet_demo/mpcpy/utils.py#L69 . I have a initially a desired path, then each time step that function is used to make a reference trajectory for that loop.
2. As far I can tell each time step the current state is used as equilibrium point for the linearization, see 4.
3. from what point of view? for the controller the accelerations are variables to be optimized (one of the outputs at the end of the optimization step), acceleration is an *input* to the state equations *f(x,u)*
4. The answer is that this MPC problem is non-linear (because  the kinematic equations are not linear), but the python solver ([cvxpy](https://www.cvxpy.org/)) only handles **convex** problems (so only linear terms), you can read more about convex vs non-convex optimization [here](https://www.solver.com/convex-optimization). This means that I had to linearize the model, this is documented in the notebook [1,0-lti-system-modelling](https://github.com/mcarfagno/mpc_python/blob/master/notebooks/1.0-lti-system-modelling.ipynb).

Does this help?

**Comment by marcs94** [comment]
thank you for the fast answer! 
1) I understood that the robot "sees" more and more pieces of trajectory as it goes, but I didn't understand the first functions of this code, that is, I didn't understand how to generate the initially desired path
2) current state of what? of the trajectory or of the vehicle? I ask about the equilibrium point also because I want to understand if the system is stable or unstable
3) from the point of view of the system (i.e. of the vehicle). So are you saying that acceleration is a control variable? Are you saying that acceleration is an input to the system? Acceleration should be a state of the system, an output of the system, not an input (I think)
4) yes, I understood this, but in the code I seem to understand that the non-linear model is used, or maybe I misunderstood it?

**Comment by mcarfagno** [comment]
1. https://github.com/mcarfagno/mpc_python/blob/7f7cdf31b4ae57fd7c9428b4fec762d90e6368a7/mpc_pybullet_demo/mpcpy/utils.py#L8
2. current state of the vehicle https://github.com/mcarfagno/mpc_python/blob/7f7cdf31b4ae57fd7c9428b4fec762d90e6368a7/mpc_pybullet_demo/mpc_demo_pybullet.py#L17 sampled from the simulation, I cant offer any help on system stability analysis
3. From the point of view of the system (car) the acceleration is modeled from as the **u** vector of the state space equations, you can rewrite the equations so that *a* is part of the **x** vector, you can read more about this [here](http://web.mit.edu/2.14/www/Handouts/StateSpace.pdf)
4. the model is linearized before being feed see, here, the matrices are LTI from Taylors series expansion.
```python
 # State Matrices
        A, B, C = mpcpy.get_linear_model_matrices(state, action)

        # Get Reference_traj -> inputs are in worldframe
        target, _ = mpcpy.get_ref_trajectory(get_state(car), path, 1.0)

        x_mpc, u_mpc = mpc.optimize_linearized_model(
            A, B, C, state, target, time_horizon=P.T, verbose=False
        )
```

**Comment by marcs94** [comment]
1) ok, the only thing that i don't understand is the type of interpolation that you've used: is it a spline or not?
2) ok, so, is the model of the vehicle a LPV or LTV model? because at each sampling step, you have a new equilibrium point, so, at each sampling step you have a new value of the matrices of the system's model
3) so, in your opinion the acceleration is the control input?
4) ok I understand this point, so we can conclude that the MPC controller uses the linearized model of the system and not the non linear model of the system. Do you have the equations of the linearized model of the system?

**Comment by mcarfagno** [comment]
For the interpolation I just used a simple linear interpolation (`interp1d` from scipy). The  equations are here --> https://github.com/mcarfagno/mpc_python/blob/master/notebooks/1.0-lti-system-modelling.ipynb

**Comment by marcs94** [comment]
Ok perfect. Can you answer at the questions 2 and 3, that are very important for me? And then, I haven't any questions

**Comment by mcarfagno** [comment]
3. for more info about the model see here --> https://www.coursera.org/lecture/intro-self-driving-cars/lesson-2-the-kinematic-bicycle-model-Bi8yE I based my equations on these
For 2 I am not sure how to answer, try checking here --> https://www.coursera.org/lecture/intro-self-driving-cars/lesson-4-advanced-steering-control-mpc-WHPvn
